//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace derinYouTube.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class competitionAnswers
    {
        public int Id { get; set; }
        public int Fk_Competition { get; set; }
        public int Fk_LiveChatMessage { get; set; }
        public int Score { get; set; }
        public bool IsValid { get; set; }
        public bool IsSubscripted { get; set; }
    
        public virtual competitions competitions { get; set; }
        public virtual liveChatMessages liveChatMessages { get; set; }
    }
}
