//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace derinYouTube.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class liveChatMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public liveChatMessages()
        {
            this.competitionAnswers = new HashSet<competitionAnswers>();
        }
    
        public int Id { get; set; }
        public string MessageId { get; set; }
        public string AuthorChannelId { get; set; }
        public string AuthorChannelUrl { get; set; }
        public string AuthorDisplayName { get; set; }
        public string LiveChatId { get; set; }
        public string VideoId { get; set; }
        public Nullable<System.DateTime> PublishedAt { get; set; }
        public Nullable<bool> HasDisplayContent { get; set; }
        public string MessageText { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsChatOwner { get; set; }
        public Nullable<bool> IsChatSponsor { get; set; }
        public Nullable<bool> IsChatModerator { get; set; }
        public bool IsMessageNumeric { get; set; }
        public string NumericMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<competitionAnswers> competitionAnswers { get; set; }
    }
}
