//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace derinYouTube.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class liveBroadcasts
    {
        public int Id { get; set; }
        public string BroadcastId { get; set; }
        public string Title { get; set; }
        public string ChannelId { get; set; }
        public string LiveChatId { get; set; }
        public string Description { get; set; }
        public string LiveStatus { get; set; }
        public string ChannelTitle { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<System.DateTime> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public Nullable<System.DateTime> ScheduledStartTime { get; set; }
    }
}
