//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace derinYouTube.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class questions
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime QuestionDate { get; set; }
    }
}
