//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace derinYouTube.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class validAnswers_vw
    {
        public int CompetitionId { get; set; }
        public string AuthorChannelId { get; set; }
        public string AuthorChannelUrl { get; set; }
        public string AuthorDisplayName { get; set; }
        public int Score { get; set; }
        public Nullable<System.DateTime> PublishedAt { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string LiveChatId { get; set; }
        public string VideoId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string MessageText { get; set; }
        public Nullable<decimal> Gap { get; set; }
        public Nullable<long> Sequence { get; set; }
    }
}
