//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace derinYouTube.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WinnerOfDay_vw
    {
        public Nullable<System.DateTime> Day { get; set; }
        public string AuthorChannelId { get; set; }
        public string AuthorChannelUrl { get; set; }
        public string AuthorDisplayName { get; set; }
        public Nullable<int> TotalScore { get; set; }
        public Nullable<int> TotalCompetition { get; set; }
        public Nullable<long> Sequence { get; set; }
    }
}
